openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'CowDogTing'
  description: 'API 명세'
servers:
  - description : API 명세
    url: http://localhost:4000/
paths:
  /api/core/userInfo:
    get:
      summary: 유저 정보 획득
      parameters:
      responses:
        '200':
          description: 유저 정보
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  image:
                    type: number
                  location:
                    type: string
                  sex: 
                    type: string
                  age: 
                    type: number
                  info: 
                    type: string
              example:
                id: "yj"
                image: 33
                location: "우만동"
                sex: "male"
                age: 25
                info: "안녕하세요"
  /api/core/joinChatInfo:
    get:
      summary: 참여 채팅방 정보 가져오기 
      parameters:
      responses:
        '200':
          description: 참여 채팅방 정보
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    chatRoomID:
                      type: number
                    notReadNum:
                      type: number
              example:
                [
                  {
                    chatRoomID: 1,
                    notReadNum: 3
                  },
                  {
                    chatRoomID: 2,
                    notReadNum: 2
                  },
                ]
  api/auth/login:
    get:
      summary: 로그인 버튼 클릭(유저 정보 받아오기)
      parameters:
      responses:
        '200':
          description: 유저 정보
          content:
            application/json:
              schema:
                type: boolean
              example:
                true
  api/auth/validation:
    get:
      summary: 회원가입(아이디 중복 검사)
      parameters:
        - name: id
          in: path
          required: true
          description: 유저 아이디
          schema:
            type: string
          example:
            "my_id"
      responses:
        '200':
          description: 회원가입 아이디 중복 검사 확인
          schema:
            type: boolean
          example:
            true



